server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jmx:
    default-domain: blockChain
  dubbo:
    application:
      name: block-chain-web
      registry:
        address: zookeeper://39.106.38.77:2181
